#
# This compose file shows how to implement a simple
#   pipeline execution based on different docker containers
#   via the depends_on keyword.
#   The checkout service clones a repository
#   The zero service runs pre-commit
#   The one service runs tests and so on.
version: '3.9'
services:
  checkout: &baseline
    image: alpine/git
    volumes:
    - ./deleteme:/code:z
    working_dir: /code
    entrypoint: ["sh"]
    command: |-
      -c '
      (test -d /code/.git
      # && git -C /code pull --rebase
      ) ||
      git clone https://github.com/teamdigitale/jsonld-semantic-playground /code
      '
  zero:
    build:
      context: ./
      dockerfile: Dockerfile.precommit
    volumes:
    - ./deleteme:/code
    working_dir: /code
    entrypoint: ['pre-commit']
    command: ['run', '-a']
    depends_on:
      checkout:
        condition: service_completed_successfully
  one:
    <<: *baseline
    build:
      context: ./
      dockerfile: Dockerfile.tox
    entrypoint: ["tox"]
    command: ["-e", "py3"]
    depends_on:
    - zero
  two:
    <<: *baseline
    image: busybox
    entrypoint: ["busybox"]
    command: ['sh', '-c', 'exit 0']
    depends_on:
    - one
  three:
    <<: *baseline
    image: busybox
    entrypoint: ["busybox"]
    command: ['sh', '-c', 'exit 0']
    depends_on:
    - two
